// @ts-nocheck
// AUTO-GENERATED by scripts/gen-web-assets.ts — do not edit by hand.
// The committed version is empty (dev serves the UI via Vite); release builds
// regenerate it so the SPA is embedded into the compiled binary.

export const WEB_ASSETS: Record<string, string> = {
};
