// @ts-nocheck
// AUTO-GENERATED by scripts/gen-web-assets.ts — do not edit by hand.
// The committed version is empty (dev serves the UI via Vite); release builds
// regenerate it so the SPA is embedded into the compiled binary.
import f0 from "../../web/dist/assets/MonacoPane-D6kYW_CN.css" with { type: "file" };
import f1 from "../../web/dist/assets/MonacoPane-DYyKCS-o.js" with { type: "file" };
import f2 from "../../web/dist/assets/abap-BrgZPUOV.js" with { type: "file" };
import f3 from "../../web/dist/assets/apex-DyP6w7ZV.js" with { type: "file" };
import f4 from "../../web/dist/assets/azcli-BaLxmfj-.js" with { type: "file" };
import f5 from "../../web/dist/assets/bat-CFOPXBzS.js" with { type: "file" };
import f6 from "../../web/dist/assets/bicep-BfEKNvv3.js" with { type: "file" };
import f7 from "../../web/dist/assets/cameligo-BFG1Mk7z.js" with { type: "file" };
import f8 from "../../web/dist/assets/clojure-DTECt2xU.js" with { type: "file" };
import f9 from "../../web/dist/assets/codicon-DCmgc-ay.ttf" with { type: "file" };
import f10 from "../../web/dist/assets/coffee-CDGzqUPQ.js" with { type: "file" };
import f11 from "../../web/dist/assets/cpp-CLLBncYj.js" with { type: "file" };
import f12 from "../../web/dist/assets/csharp-dUCx_-0o.js" with { type: "file" };
import f13 from "../../web/dist/assets/csp-5Rap-vPy.js" with { type: "file" };
import f14 from "../../web/dist/assets/css-D3h14YRZ.js" with { type: "file" };
import f15 from "../../web/dist/assets/css.worker-BRIrhzkG.js" with { type: "file" };
import f16 from "../../web/dist/assets/cssMode-CTvM571o.js" with { type: "file" };
import f17 from "../../web/dist/assets/cypher-DrQuvNYM.js" with { type: "file" };
import f18 from "../../web/dist/assets/dart-CFKIUWau.js" with { type: "file" };
import f19 from "../../web/dist/assets/dockerfile-Zznr-cwX.js" with { type: "file" };
import f20 from "../../web/dist/assets/ecl-Ce3n6wWz.js" with { type: "file" };
import f21 from "../../web/dist/assets/editor.worker-DX6ApQqM.js" with { type: "file" };
import f22 from "../../web/dist/assets/elixir-deUWdS0T.js" with { type: "file" };
import f23 from "../../web/dist/assets/flow9-i9-g7ZhI.js" with { type: "file" };
import f24 from "../../web/dist/assets/freemarker2-DAVRAzGj.js" with { type: "file" };
import f25 from "../../web/dist/assets/fsharp-CzKuDChf.js" with { type: "file" };
import f26 from "../../web/dist/assets/go-Cphgjts3.js" with { type: "file" };
import f27 from "../../web/dist/assets/graphql-Cg7bfA9N.js" with { type: "file" };
import f28 from "../../web/dist/assets/handlebars-C60fRUCG.js" with { type: "file" };
import f29 from "../../web/dist/assets/hcl-0cvrggvQ.js" with { type: "file" };
import f30 from "../../web/dist/assets/html-Du1VRwTe.js" with { type: "file" };
import f31 from "../../web/dist/assets/html.worker-CBI4EQBP.js" with { type: "file" };
import f32 from "../../web/dist/assets/htmlMode-C7LcMACy.js" with { type: "file" };
import f33 from "../../web/dist/assets/index-B6f_Puc-.js" with { type: "file" };
import f34 from "../../web/dist/assets/index-DGLvTulP.css" with { type: "file" };
import f35 from "../../web/dist/assets/ini-Drc7WvVn.js" with { type: "file" };
import f36 from "../../web/dist/assets/java-B_fMsGYe.js" with { type: "file" };
import f37 from "../../web/dist/assets/javascript-D0Aya_dx.js" with { type: "file" };
import f38 from "../../web/dist/assets/json.worker-CIZWV9vN.js" with { type: "file" };
import f39 from "../../web/dist/assets/jsonMode-BwkTXR4L.js" with { type: "file" };
import f40 from "../../web/dist/assets/julia-Bqgm2twL.js" with { type: "file" };
import f41 from "../../web/dist/assets/kotlin-BSkB5QuD.js" with { type: "file" };
import f42 from "../../web/dist/assets/less-BsTHnhdd.js" with { type: "file" };
import f43 from "../../web/dist/assets/lexon-YWi4-JPR.js" with { type: "file" };
import f44 from "../../web/dist/assets/liquid-CDghZNg6.js" with { type: "file" };
import f45 from "../../web/dist/assets/lua-nf6ki56Z.js" with { type: "file" };
import f46 from "../../web/dist/assets/m3-Cpb6xl2v.js" with { type: "file" };
import f47 from "../../web/dist/assets/markdown-DSZPf7rp.js" with { type: "file" };
import f48 from "../../web/dist/assets/mdx-B1EdbC8L.js" with { type: "file" };
import f49 from "../../web/dist/assets/mips-B_c3zf-v.js" with { type: "file" };
import f50 from "../../web/dist/assets/msdax-rUNN04Wq.js" with { type: "file" };
import f51 from "../../web/dist/assets/mysql-DDwshQtU.js" with { type: "file" };
import f52 from "../../web/dist/assets/objective-c-B5zXfXm9.js" with { type: "file" };
import f53 from "../../web/dist/assets/pascal-CXOwvkN_.js" with { type: "file" };
import f54 from "../../web/dist/assets/pascaligo-Bc-ZgV77.js" with { type: "file" };
import f55 from "../../web/dist/assets/perl-CwNk8-XU.js" with { type: "file" };
import f56 from "../../web/dist/assets/pgsql-tGk8EFnU.js" with { type: "file" };
import f57 from "../../web/dist/assets/php-CpIb_Oan.js" with { type: "file" };
import f58 from "../../web/dist/assets/pla-B03wrqEc.js" with { type: "file" };
import f59 from "../../web/dist/assets/postiats-BKlk5iyT.js" with { type: "file" };
import f60 from "../../web/dist/assets/powerquery-Bhzvs7bI.js" with { type: "file" };
import f61 from "../../web/dist/assets/powershell-Dd3NCNK9.js" with { type: "file" };
import f62 from "../../web/dist/assets/protobuf-COyEY5Pt.js" with { type: "file" };
import f63 from "../../web/dist/assets/pug-BaJupSGV.js" with { type: "file" };
import f64 from "../../web/dist/assets/python-BYSpCDmc.js" with { type: "file" };
import f65 from "../../web/dist/assets/qsharp-DXyYeYxl.js" with { type: "file" };
import f66 from "../../web/dist/assets/r-CdQndTaG.js" with { type: "file" };
import f67 from "../../web/dist/assets/razor-D4jRSTo6.js" with { type: "file" };
import f68 from "../../web/dist/assets/redis-CVwtpugi.js" with { type: "file" };
import f69 from "../../web/dist/assets/redshift-25W9uPmb.js" with { type: "file" };
import f70 from "../../web/dist/assets/restructuredtext-DfzH4Xui.js" with { type: "file" };
import f71 from "../../web/dist/assets/ruby-Cp1zYvxS.js" with { type: "file" };
import f72 from "../../web/dist/assets/rust-D5C2fndG.js" with { type: "file" };
import f73 from "../../web/dist/assets/sb-CDntyWJ8.js" with { type: "file" };
import f74 from "../../web/dist/assets/scala-BoFRg7Ot.js" with { type: "file" };
import f75 from "../../web/dist/assets/scheme-Bio4gycK.js" with { type: "file" };
import f76 from "../../web/dist/assets/scss-4Ik7cdeQ.js" with { type: "file" };
import f77 from "../../web/dist/assets/shell-CX-rkNHf.js" with { type: "file" };
import f78 from "../../web/dist/assets/solidity-Tw7wswEv.js" with { type: "file" };
import f79 from "../../web/dist/assets/sophia-C5WLch3f.js" with { type: "file" };
import f80 from "../../web/dist/assets/sparql-DHaeiCBh.js" with { type: "file" };
import f81 from "../../web/dist/assets/sql-CCSDG5nI.js" with { type: "file" };
import f82 from "../../web/dist/assets/st-pnP8ivHi.js" with { type: "file" };
import f83 from "../../web/dist/assets/swift-DwJ7jVG9.js" with { type: "file" };
import f84 from "../../web/dist/assets/systemverilog-B9Xyijhd.js" with { type: "file" };
import f85 from "../../web/dist/assets/tcl-DnHyzjbg.js" with { type: "file" };
import f86 from "../../web/dist/assets/ts.worker-Ds4I2Msu.js" with { type: "file" };
import f87 from "../../web/dist/assets/tsMode-CmiZGRWt.js" with { type: "file" };
import f88 from "../../web/dist/assets/twig-CPajHgWi.js" with { type: "file" };
import f89 from "../../web/dist/assets/typescript-BqoaoiGT.js" with { type: "file" };
import f90 from "../../web/dist/assets/typespec-D-MeaMDU.js" with { type: "file" };
import f91 from "../../web/dist/assets/vb-DgyLZaXg.js" with { type: "file" };
import f92 from "../../web/dist/assets/wgsl-BIv9DU6q.js" with { type: "file" };
import f93 from "../../web/dist/assets/xml-DZVVk4_G.js" with { type: "file" };
import f94 from "../../web/dist/assets/yaml-ULTQ2L6U.js" with { type: "file" };
import f95 from "../../web/dist/index.html" with { type: "file" };

export const WEB_ASSETS: Record<string, string> = {
    "/assets/MonacoPane-D6kYW_CN.css": f0,
    "/assets/MonacoPane-DYyKCS-o.js": f1,
    "/assets/abap-BrgZPUOV.js": f2,
    "/assets/apex-DyP6w7ZV.js": f3,
    "/assets/azcli-BaLxmfj-.js": f4,
    "/assets/bat-CFOPXBzS.js": f5,
    "/assets/bicep-BfEKNvv3.js": f6,
    "/assets/cameligo-BFG1Mk7z.js": f7,
    "/assets/clojure-DTECt2xU.js": f8,
    "/assets/codicon-DCmgc-ay.ttf": f9,
    "/assets/coffee-CDGzqUPQ.js": f10,
    "/assets/cpp-CLLBncYj.js": f11,
    "/assets/csharp-dUCx_-0o.js": f12,
    "/assets/csp-5Rap-vPy.js": f13,
    "/assets/css-D3h14YRZ.js": f14,
    "/assets/css.worker-BRIrhzkG.js": f15,
    "/assets/cssMode-CTvM571o.js": f16,
    "/assets/cypher-DrQuvNYM.js": f17,
    "/assets/dart-CFKIUWau.js": f18,
    "/assets/dockerfile-Zznr-cwX.js": f19,
    "/assets/ecl-Ce3n6wWz.js": f20,
    "/assets/editor.worker-DX6ApQqM.js": f21,
    "/assets/elixir-deUWdS0T.js": f22,
    "/assets/flow9-i9-g7ZhI.js": f23,
    "/assets/freemarker2-DAVRAzGj.js": f24,
    "/assets/fsharp-CzKuDChf.js": f25,
    "/assets/go-Cphgjts3.js": f26,
    "/assets/graphql-Cg7bfA9N.js": f27,
    "/assets/handlebars-C60fRUCG.js": f28,
    "/assets/hcl-0cvrggvQ.js": f29,
    "/assets/html-Du1VRwTe.js": f30,
    "/assets/html.worker-CBI4EQBP.js": f31,
    "/assets/htmlMode-C7LcMACy.js": f32,
    "/assets/index-B6f_Puc-.js": f33,
    "/assets/index-DGLvTulP.css": f34,
    "/assets/ini-Drc7WvVn.js": f35,
    "/assets/java-B_fMsGYe.js": f36,
    "/assets/javascript-D0Aya_dx.js": f37,
    "/assets/json.worker-CIZWV9vN.js": f38,
    "/assets/jsonMode-BwkTXR4L.js": f39,
    "/assets/julia-Bqgm2twL.js": f40,
    "/assets/kotlin-BSkB5QuD.js": f41,
    "/assets/less-BsTHnhdd.js": f42,
    "/assets/lexon-YWi4-JPR.js": f43,
    "/assets/liquid-CDghZNg6.js": f44,
    "/assets/lua-nf6ki56Z.js": f45,
    "/assets/m3-Cpb6xl2v.js": f46,
    "/assets/markdown-DSZPf7rp.js": f47,
    "/assets/mdx-B1EdbC8L.js": f48,
    "/assets/mips-B_c3zf-v.js": f49,
    "/assets/msdax-rUNN04Wq.js": f50,
    "/assets/mysql-DDwshQtU.js": f51,
    "/assets/objective-c-B5zXfXm9.js": f52,
    "/assets/pascal-CXOwvkN_.js": f53,
    "/assets/pascaligo-Bc-ZgV77.js": f54,
    "/assets/perl-CwNk8-XU.js": f55,
    "/assets/pgsql-tGk8EFnU.js": f56,
    "/assets/php-CpIb_Oan.js": f57,
    "/assets/pla-B03wrqEc.js": f58,
    "/assets/postiats-BKlk5iyT.js": f59,
    "/assets/powerquery-Bhzvs7bI.js": f60,
    "/assets/powershell-Dd3NCNK9.js": f61,
    "/assets/protobuf-COyEY5Pt.js": f62,
    "/assets/pug-BaJupSGV.js": f63,
    "/assets/python-BYSpCDmc.js": f64,
    "/assets/qsharp-DXyYeYxl.js": f65,
    "/assets/r-CdQndTaG.js": f66,
    "/assets/razor-D4jRSTo6.js": f67,
    "/assets/redis-CVwtpugi.js": f68,
    "/assets/redshift-25W9uPmb.js": f69,
    "/assets/restructuredtext-DfzH4Xui.js": f70,
    "/assets/ruby-Cp1zYvxS.js": f71,
    "/assets/rust-D5C2fndG.js": f72,
    "/assets/sb-CDntyWJ8.js": f73,
    "/assets/scala-BoFRg7Ot.js": f74,
    "/assets/scheme-Bio4gycK.js": f75,
    "/assets/scss-4Ik7cdeQ.js": f76,
    "/assets/shell-CX-rkNHf.js": f77,
    "/assets/solidity-Tw7wswEv.js": f78,
    "/assets/sophia-C5WLch3f.js": f79,
    "/assets/sparql-DHaeiCBh.js": f80,
    "/assets/sql-CCSDG5nI.js": f81,
    "/assets/st-pnP8ivHi.js": f82,
    "/assets/swift-DwJ7jVG9.js": f83,
    "/assets/systemverilog-B9Xyijhd.js": f84,
    "/assets/tcl-DnHyzjbg.js": f85,
    "/assets/ts.worker-Ds4I2Msu.js": f86,
    "/assets/tsMode-CmiZGRWt.js": f87,
    "/assets/twig-CPajHgWi.js": f88,
    "/assets/typescript-BqoaoiGT.js": f89,
    "/assets/typespec-D-MeaMDU.js": f90,
    "/assets/vb-DgyLZaXg.js": f91,
    "/assets/wgsl-BIv9DU6q.js": f92,
    "/assets/xml-DZVVk4_G.js": f93,
    "/assets/yaml-ULTQ2L6U.js": f94,
    "/index.html": f95,
    "/": f95,
};
