#!/usr/bin/env bun
// Scan the built web SPA (apps/web/dist) and emit apps/server/src/web-assets.generated.ts,
// which statically imports every asset with `{ type: "file" }`. Those imports are what
// `bun build --compile` bundles into the single binary; at runtime each import resolves to
// a path that `Bun.file()` can read (an embedded blob in the compiled binary, a real file
// otherwise). Hash-named Vite/Monaco chunks can't be hardcoded, hence this codegen step.
import { readdir } from "node:fs/promises";
import * as path from "node:path";

const ROOT = path.resolve(import.meta.dir, "..");
const DIST = path.join(ROOT, "apps/web/dist");
const OUT = path.join(ROOT, "apps/server/src/web-assets.generated.ts");
// Import specifiers are relative to the generated file's directory (apps/server/src).
const IMPORT_PREFIX = "../../web/dist";

async function walk(dir: string): Promise<string[]> {
    const entries = await readdir(dir, { withFileTypes: true });
    const files: string[] = [];
    for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            files.push(...(await walk(full)));
        } else {
            files.push(full);
        }
    }
    return files;
}

const files = (await walk(DIST)).sort();
if (files.length === 0) {
    throw new Error(`No files found in ${DIST}; run the web build first.`);
}

const imports: string[] = [];
const entries: string[] = [];
files.forEach((file, i) => {
    const rel = path.relative(DIST, file).split(path.sep).join("/");
    const route = `/${rel}`;
    const name = `f${i}`;
    imports.push(`import ${name} from "${IMPORT_PREFIX}/${rel}" with { type: "file" };`);
    entries.push(`    ${JSON.stringify(route)}: ${name},`);
    if (rel === "index.html") {
        entries.push(`    "/": ${name},`);
    }
});

const out = `// @ts-nocheck
// AUTO-GENERATED by scripts/gen-web-assets.ts — do not edit by hand.
// The committed version is empty (dev serves the UI via Vite); release builds
// regenerate it so the SPA is embedded into the compiled binary.
${imports.join("\n")}

export const WEB_ASSETS: Record<string, string> = {
${entries.join("\n")}
};
`;

await Bun.write(OUT, out);
console.log(`Embedded ${files.length} web assets → ${path.relative(ROOT, OUT)}`);
