// AUTO-GENERATED by scripts/build-agent.sh — do not edit by hand.
// The committed version is empty (source runs, tests, and release builds get a plain
// x.y.z AGENT_VERSION). A local `bun run build:agent` stamps a git-commit suffix here
// so dev builds carry a distinguishable version, then restores this file on exit.
export const DEV_SUFFIX = "-dev.21a685d6.dirty";
